In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l
# y = wx + b

In [3]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [4]:
def load_array(data_arrays, batch_size, is_train = True): #@save
    '''构造一个PyTorch数据迭代器'''
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle = is_train)

In [5]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [6]:
next(iter(data_iter))

[tensor([[ 0.2001,  1.6271],
         [ 1.3237,  0.1460],
         [ 1.4999,  1.0195],
         [ 1.6863, -0.4311],
         [-0.2659,  0.3557],
         [ 2.3573, -0.4873],
         [ 0.0669, -0.4082],
         [-0.4644,  2.4970],
         [ 0.1838, -0.0681],
         [ 0.0385, -0.2310]]),
 tensor([[-0.9407],
         [ 6.3378],
         [ 3.7353],
         [ 9.0310],
         [ 2.4499],
         [10.5609],
         [ 5.7067],
         [-5.2189],
         [ 4.7755],
         [ 5.0527]])]

In [7]:
# nn is the abbr for neural network
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))

In [8]:
# initialize the parameters
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [9]:
loss = nn.MSELoss()

In [11]:
trainer = torch.optim.SGD(net.parameters(), lr = 0.03)

In [22]:
num_epoch = 3
for epoch in range(num_epoch):
    # optimizing process
    for X, y in data_iter:   # data_iter here serves as a dataset
                             # batch_size is included in data_iter
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f"Epoch {epoch+1} loss {l:f}")
    

Epoch 1 loss 0.000101
Epoch 2 loss 0.000099
Epoch 3 loss 0.000100


In [24]:
w = net[0].weight.data
b = net[0].bias.data
print(true_w - w.reshape(true_w.shape))
print(true_b - b)

tensor([-0.0006, -0.0006])
tensor([-9.8228e-05])
