In [17]:
import torch
import numpy as np
import torch.nn as nn
from torch import optim as optim 
import torch.nn.functional as F

5->8全连接
x (1, 5)
y (1, 8)
W (5, 8)
b (8,)

In [18]:
w = torch.randn(5, 8, requires_grad = True)
b = torch.randn(8, requires_grad = True)
x = torch.randn(1, 5)
Y = torch.randn(1, 8)

In [19]:
y = F.relu(x @ w + b)
y

tensor([[0.0000, 0.0578, 0.4845, 0.0000, 0.5265, 0.0000, 0.0000, 0.0131]],
       grad_fn=<ReluBackward0>)

In [20]:
loss = F.cross_entropy(y, Y)   #包含one-hot
loss

tensor(0.3902, grad_fn=<DivBackward1>)

In [21]:
loss.backward()
w.grad

tensor([[-0.0000e+00, -1.3415e+00,  1.1907e+00, -0.0000e+00,  1.4819e-01,
         -0.0000e+00, -0.0000e+00, -9.9026e-03],
        [-0.0000e+00, -5.1676e-01,  4.5866e-01, -0.0000e+00,  5.7085e-02,
         -0.0000e+00, -0.0000e+00, -3.8146e-03],
        [-0.0000e+00, -9.3614e-03,  8.3089e-03, -0.0000e+00,  1.0341e-03,
         -0.0000e+00, -0.0000e+00, -6.9104e-05],
        [ 0.0000e+00,  2.6369e-01, -2.3404e-01,  0.0000e+00, -2.9129e-02,
          0.0000e+00,  0.0000e+00,  1.9465e-03],
        [-0.0000e+00, -8.0713e-01,  7.1638e-01, -0.0000e+00,  8.9162e-02,
         -0.0000e+00, -0.0000e+00, -5.9581e-03]])

In [22]:
b.grad

tensor([ 0.0000,  1.4334, -1.2722,  0.0000, -0.1583,  0.0000,  0.0000,  0.0106])

搭建模型

In [23]:
class M_CNN(nn.Module):
    def __init__(self):   #定义各个层
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size = 3, padding = 1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size = 3, padding = 1)
        self.bn1 = nn.BatchNorm2d(16)  #批量规范化
        self.bn2 = nn.BatchNorm2d(32)
        self.MaxPool = nn.MaxPool2d(kernel_size = 2)   #定义一个，可复用
        #self.lstm = nn.LSTM()
        #self.emb = nn.Embedding()
        self.fc1 = nn.Linear(12*12*32, 100)   # 100个神经元的隐藏层
        self.fc2 = nn.Linear(100, 7)
    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = self.MaxPool(x)
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.MaxPool(x)
        x = x.view(-1, 12*12*32)  #相当于flatten
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x
    

数据处理

In [24]:
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.datasets import ImageFolder

In [26]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean = (0.5,), std = (0.5,))])

In [28]:
dataset = ImageFolder(r'C:\Users\ASUS\Documents\WPSDrive\1547059483\WPS企业云盘\清华大学\我的企业文档\instant\images', transform = transform)
dataloader = DataLoader(dataset, batch_size = 32, shuffle = True)

FileNotFoundError: Couldn't find any class folder in C:\Users\ASUS\Documents\WPSDrive\1547059483\WPS企业云盘\清华大学\我的企业文档\instant\images.